export const classOptions = {
  padding: {
    label: "Padding",
    options: [
      { value: "", label: "None" },
      { value: "p-0", label: "p-0" },
      { value: "p-1", label: "p-1" },
      { value: "p-2", label: "p-2" },
      { value: "p-3", label: "p-3" },
      { value: "p-4", label: "p-4" },
      { value: "p-5", label: "p-5" },
    ],
  },
  paddingTop: {
    label: "Padding Top",
    options: [
      { value: "", label: "None" },
      { value: "pt-1", label: "pt-1" },
      { value: "pt-2", label: "pt-2" },
      { value: "pt-3", label: "pt-3" },
      { value: "pt-4", label: "pt-4" },
      { value: "pt-5", label: "pt-5" },
    ],
  },
  paddingBottom: {
    label: "Padding Bottom",
    options: [
      { value: "", label: "None" },
      { value: "pb-1", label: "pb-1" },
      { value: "pb-2", label: "pb-2" },
      { value: "pb-3", label: "pb-3" },
      { value: "pb-4", label: "pb-4" },
      { value: "pb-5", label: "pb-5" },
    ],
  },
  paddingLeft: {
    label: "Padding Left",
    options: [
      { value: "", label: "None" },
      { value: "ps-1", label: "ps-1" },
      { value: "ps-2", label: "ps-2" },
      { value: "ps-3", label: "ps-3" },
      { value: "ps-4", label: "ps-4" },
      { value: "ps-5", label: "ps-5" },
    ],
  },
  paddingRight: {
    label: "Padding Right",
    options: [
      { value: "", label: "None" },
      { value: "pe-1", label: "pe-1" },
      { value: "pe-2", label: "pe-2" },
      { value: "pe-3", label: "pe-3" },
      { value: "pe-4", label: "pe-4" },
      { value: "pe-5", label: "pe-5" },
    ],
  },
  margin: {
    label: "Margin",
    options: [
      { value: "", label: "None" },
      { value: "m-0", label: "m-0" },
      { value: "m-1", label: "m-1" },
      { value: "m-2", label: "m-2" },
      { value: "m-3", label: "m-3" },
      { value: "m-4", label: "m-4" },
      { value: "m-5", label: "m-5" },
    ],
  },
  marginTop: {
    label: "Margin Top",
    options: [
      { value: "", label: "None" },
      { value: "mt-1", label: "mt-1" },
      { value: "mt-2", label: "mt-2" },
      { value: "mt-3", label: "mt-3" },
      { value: "mt-4", label: "mt-4" },
      { value: "mt-5", label: "mt-5" },
    ],
  },
  marginBottom: {
    label: "Margin Bottom",
    options: [
      { value: "", label: "None" },
      { value: "mb-1", label: "mb-1" },
      { value: "mb-2", label: "mb-2" },
      { value: "mb-3", label: "mb-3" },
      { value: "mb-4", label: "mb-4" },
      { value: "mb-5", label: "mb-5" },
    ],
  },
  marginLeft: {
    label: "Margin Left",
    options: [
      { value: "", label: "None" },
      { value: "ms-1", label: "ms-1" },
      { value: "ms-2", label: "ms-2" },
      { value: "ms-3", label: "ms-3" },
      { value: "ms-4", label: "ms-4" },
      { value: "ms-5", label: "ms-5" },
    ],
  },
  marginRight: {
    label: "Margin Right",
    options: [
      { value: "", label: "None" },
      { value: "me-1", label: "me-1" },
      { value: "me-2", label: "me-2" },
      { value: "me-3", label: "me-3" },
      { value: "me-4", label: "me-4" },
      { value: "me-5", label: "me-5" },
    ],
  },
  background: {
    label: "Background Color",
    options: [
      { value: "", label: "None" },
      { value: "bg-primary", label: "Primary" },
      { value: "bg-secondary", label: "Secondary" },
      { value: "bg-success", label: "Success" },
      { value: "bg-danger", label: "Danger" },
      { value: "bg-warning", label: "Warning" },
      { value: "bg-info", label: "Info" },
      { value: "bg-light", label: "Light" },
      { value: "bg-dark", label: "Dark" },
      { value: "bg-white", label: "White" },
      { value: "bg-transparent", label: "Transparent" },
    ],
  },
  textColor: {
    label: "Text Color",
    options: [
      { value: "", label: "Default" },
      { value: "text-primary", label: "Primary" },
      { value: "text-secondary", label: "Secondary" },
      { value: "text-success", label: "Success" },
      { value: "text-danger", label: "Danger" },
      { value: "text-warning", label: "Warning" },
      { value: "text-info", label: "Info" },
      { value: "text-light", label: "Light" },
      { value: "text-dark", label: "Dark" },
      { value: "text-white", label: "White" },
      { value: "text-muted", label: "Muted" },
    ],
  },
  border: {
    label: "Border",
    options: [
      { value: "", label: "None" },
      { value: "border", label: "All sides" },
      { value: "border-top", label: "Top" },
      { value: "border-end", label: "End" },
      { value: "border-bottom", label: "Bottom" },
      { value: "border-start", label: "Start" },
    ],
  },
  borderColor: {
    label: "Border Color",
    options: [
      { value: "", label: "Default" },
      { value: "border-primary", label: "Primary" },
      { value: "border-secondary", label: "Secondary" },
      { value: "border-success", label: "Success" },
      { value: "border-danger", label: "Danger" },
      { value: "border-warning", label: "Warning" },
      { value: "border-info", label: "Info" },
      { value: "border-light", label: "Light" },
      { value: "border-dark", label: "Dark" },
      { value: "border-white", label: "White" },
    ],
  },
  width: {
    label: "Width",
    options: [
      { value: "", label: "Auto" },
      { value: "w-25", label: "25%" },
      { value: "w-50", label: "50%" },
      { value: "w-75", label: "75%" },
      { value: "w-100", label: "100%" },
      { value: "w-auto", label: "Auto" },
    ],
  },
  height: {
    label: "Height",
    options: [
      { value: "", label: "Auto" },
      { value: "h-25", label: "25%" },
      { value: "h-50", label: "50%" },
      { value: "h-75", label: "75%" },
      { value: "h-100", label: "100%" },
      { value: "h-auto", label: "Auto" },
    ],
  },
  shadow: {
    label: "Shadow",
    options: [
      { value: "", label: "None" },
      { value: "shadow-none", label: "No Shadow" },
      { value: "shadow-sm", label: "Small" },
      { value: "shadow", label: "Regular" },
      { value: "shadow-lg", label: "Large" },
    ],
  },
  rounded: {
    label: "Rounded",
    options: [
      { value: "", label: "None" },
      { value: "rounded", label: "All corners" },
      { value: "rounded-0", label: "No rounding" },
      { value: "rounded-1", label: "Small" },
      { value: "rounded-2", label: "Medium" },
      { value: "rounded-3", label: "Large" },
    ],
  },
  roundedCorner: {
    label: "Rounded Corner",
    options: [
      { value: "", label: "Default" },
      { value: "rounded-top", label: "Top" },
      { value: "rounded-end", label: "End" },
      { value: "rounded-bottom", label: "Bottom" },
      { value: "rounded-start", label: "Start" },
      { value: "rounded-circle", label: "Circle" },
      { value: "rounded-pill", label: "Pill" },
    ],
  },
  fontSize: {
    label: "Font Size",
    options: [
      { value: "", label: "Default" },
      { value: "fs-1", label: "Largest" },
      { value: "fs-2", label: "Larger" },
      { value: "fs-3", label: "Large" },
      { value: "fs-4", label: "Medium" },
      { value: "fs-5", label: "Small" },
      { value: "fs-6", label: "Smallest" },
    ],
  },
  fontWeight: {
    label: "Font Weight",
    options: [
      { value: "", label: "Default" },
      { value: "fw-light", label: "Light" },
      { value: "fw-lighter", label: "Lighter" },
      { value: "fw-normal", label: "Normal" },
      { value: "fw-bold", label: "Bold" },
      { value: "fw-bolder", label: "Bolder" },
    ],
  },
  textAlign: {
    label: "Text Align",
    options: [
      { value: "", label: "Default" },
      { value: "text-start", label: "Start" },
      { value: "text-end", label: "End" },
      { value: "text-center", label: "Center" },
      { value: "text-justify", label: "Justify" },
    ],
  },
  opacity: {
    label: "Opacity",
    options: [
      { value: "", label: "Default" },
      { value: "opacity-0", label: "0%" },
      { value: "opacity-25", label: "25%" },
      { value: "opacity-50", label: "50%" },
      { value: "opacity-75", label: "75%" },
      { value: "opacity-100", label: "100%" },
    ],
  },
  display: {
    label: "Display",
    options: [
      { value: "", label: "Default" },
      { value: "d-none", label: "None" },
      { value: "d-inline", label: "Inline" },
      { value: "d-inline-block", label: "Inline Block" },
      { value: "d-block", label: "Block" },
      { value: "d-flex", label: "Flex" },
      { value: "d-grid", label: "Grid" },
    ],
  },
};
