/**
 * Template data for CTA cards
 * This file contains predefined templates for the Dynamic CTA Creator
 */

export const templateData = [
  {
    id: 4,
    name: "DAPT",
    Json: {},
    Type: {},
    Type_id: "",
    consent_statement: "",
    Position: "",

    data: {
      tag: {
        text: "",
        position: "",
        bgColor: "",
        textColor: "",
        borderRadius: "",
        bgOpacity: "",
        extraClass: "",
      },
      title: {
        content: "Clopldogrel and Aspirin (DAPT)",
        variation: "h4",
        opacity: "text-opacity-100",
        color: "dark",
        startEndorment: "",
        endEndorment: "",
        extraClass: "justify-content-center",
      },
      paragraph: {
        content:
          "Our dedicated support team is available to provide timely information and address your inquiries with utmost assistance.",
        opacity: "text-opacity-100",
        color: "dark",
        extraClass: "mt-2",
      },
      button: [
        {
          url: "",
          content: "Click here to Know More",
          variation: "btn-primary",
          size: "",
          position: "center",
          startEndorment: "",
          endEndorment: "",
          extraClass: "px-4 fw-medium fs-5",
        },
      ],
      cardStyle: {
        cardbgcolor: "white",
        color: "primary",
        cardbgopacity: "bg-opacity-10",
        border: "",
        borderColor: "",
        borderOpacity: "",
        borderWidth: "rounded-3",
        extraClass: "",
        borderRadius: "",
      },
      imageObject: [
        {
          url: "https://clirnet-cms.b-cdn.net/medwiki/43_server/video/1696423230_1688713284_78rr-removebg-preview_(1).png?tr=w-411,h-108,pr=true,c-at_max",
          position: "top-right",
          size: "30px",
          alt: "image text",
          extraClass: "",
        },
      ],
    },
  },
  {
    id: 1,
    name: "Magazine Download",
    data: {
      tag: {
        text: "",
        position: "",
        bgColor: "",
        textColor: "",
        borderRadius: "",
        bgOpacity: "",
        extraClass: "",
      },
      title: {
        content: "Decoction 2023: The Official E-Magazine of IMA-MSN UP",
        variation: "h4",
        opacity: "text-opacity-100",
        color: "dark",
        startEndorment: "",
        endEndorment: "",
        extraClass: "pt-3",
      },
      paragraph: {
        content: "<p>Click to Download the full Report Now!</p>",
        opacity: "text-opacity-100",
        color: "dark",
        extraClass: "pt-3",
      },
      button: [
        {
          url: "",
          content: "Download Magazine",
          variation: "btn-link",
          size: "",
          position: "left",
          startEndorment: "",
          endEndorment: "",
          extraClass: "mb-3 p-0 ms-3 text-decoration-none fw-medium",
        },
      ],
      cardStyle: {
        cardbgcolor: "white",
        color: "primary",
        cardbgopacity: "bg-opacity-10",
        border: "",
        borderColor: "",
        borderOpacity: "",
        borderWidth: "rounded-3",
        extraClass: "",
        borderRadius: "",
      },
      imageObject: [
        {
          url: "",
          position: "",
          size: "",
          alt: "",
          extraClass: "",
        },
      ],
    },
  },
  {
    id: 2,
    name: "Anxiety Treatment",
    data: {
      tag: {
        text: "Recommended For You",
        position: "left",
        bgColor: "",
        textColor: "dark",
        borderRadius: "rounded-start",
        bgOpacity: "bg-opacity-10",
        extraClass: "mt-3 ms-3",
      },
      title: {
        content: "Longstanding Treatment For Anxiety",
        variation: "sub_header",
        opacity: "text-opacity-100",
        color: "dark",
        startEndorment: "",
        endEndorment: "",
        extraClass: "justify-content-center fs-4 fw-semibold lh-base",
      },
      paragraph: {
        content: "<h5>Precise Dosage and Recommendation</h5>",
        opacity: "text-opacity-100",
        color: "dark",
        extraClass: "pt-3",
      },
      button: [
        {
          url: "",
          content: "Read Now",
          variation: "btn-primary",
          size: "w-100",
          position: "center",
          startEndorment: "",
          endEndorment: "",
          extraClass: "py-3 fw-semibold fs-5",
        },
      ],
      cardStyle: {
        cardbgcolor: "white",
        color: "primary",
        cardbgopacity: "bg-opacity-10",
        border: "",
        borderColor: "",
        borderOpacity: "",
        borderWidth: "rounded-3",
        extraClass: "",
        borderRadius: "",
      },
      imageObject: [
        {
          url: "https://img-cdn.clirnet.com/medwiki/43_server/video/1722859266_1654599815_having-schizophrenia-and-paranoia-can-be-lonely.png",
          position: "top-right",
          size: "45px",
          alt: "image text",
          extraClass: "",
        },
      ],
    },
  },
  {
    id: 3,
    name: "Cough Syrup",
    data: {
      tag: {
        text: "",
        position: "right",
        bgColor: "primary",
        textColor: "#581",
        borderRadius: "rounded-start",
        bgOpacity: "bg-opacity-50",
        extraClass: "p-2",
      },
      title: {
        content: "<h2>Reliable cough syrup</h2>",
        variation: "sub_header",
        opacity: "text-opacity-100",
        color: "black",
        startEndorment: "",
        endEndorment: "",
        extraClass: "fw-bold",
      },
      paragraph: {
        content:
          "<h5>To alleviate the symptoms of chronic inflammatory bronchial disorder use propan</h5>",
        opacity: "text-opacity-75",
        color: "dark",
        extraClass: "pt-3",
      },
      button: [
        {
          url: "",
          content: "Click here",
          variation: "btn-primary",
          size: "w-75",
          position: "left",
          startEndorment: "",
          endEndorment: "",
          extraClass: "py-3 fw-semibold fs-5",
        },
      ],
      cardStyle: {
        cardbgcolor: "white",
        color: "primary",
        cardbgopacity: "bg-opacity-10",
        border: "",
        borderColor: "",
        borderOpacity: "",
        borderWidth: "rounded-3",
        extraClass: "",
        borderRadius: "",
      },
      imageObject: [
        {
          url: "https://img-cdn.clirnet.com/medwiki/43_server/video/1722859479_1720592599_1689582685_Prospan.png",
          position: "top-right",
          size: "36px",
          alt: "image text",
          extraClass: "",
        },
      ],
    },
  },
  {
    id: 45,
    name: "Ashvagandha",
    data: {
      tag: {
        text: "",
        position: "",
        bgColor: "",
        textColor: "",
        borderRadius: "",
        bgOpacity: "",
        extraClass: "",
      },
      title: {
        content: "Expert Talks",
        variation: "h4",
        opacity: "text-opacity-100",
        color: "dark",
        startEndorment: "",
        endEndorment: "",
        extraClass: "justify-content-center",
      },
      paragraph: {
        content:
          '<div><h6 style="padding-bottom: 8px">Advertisement</h6><h5>Join now to discover the latest insights on Pertussis Awareness, shared by leading experts in the field.</h5></div>',
        opacity: "text-opacity-100",
        color: "dark",
        extraClass: "mt-2",
      },
      button: [
        {
          url: "https://webstreamlive.com/gsk/in/14052025/index.html",
          content: "Register Now",
          variation: "btn-primary",
          size: "",
          position: "center",
          startEndorment: "",
          endEndorment: "",
          consent_statement:
            "You hereby give your consent to GSK to share relevant information with you through e-mail, SMS, Telecalling and WhatsApp for Doctors, from time to time.",
          extraClass: "px-4 fw-medium fs-5",
        },
      ],
      cardStyle: {
        cardbgcolor: "white",
        color: "primary",
        cardbgopacity: "bg-opacity-10",
        border: "",
        borderColor: "",
        borderOpacity: "",
        borderWidth: "rounded-3",
        extraClass: "shadow",
        borderRadius: "",
      },
      imageObject: [
        {
          url: "https://storage.googleapis.com/medwiki/43_server/video/1748513062_GSK_Logo_(1).png",
          position: "top-right",
          size: "30px",
          alt: "image text",
          extraClass: "",
        },
      ],
    },
  },
  {
    id: 5,
    name: "Ashvagandha",
    data: {
      tag: {
        text: "",
        position: "",
        bgColor: "",
        textColor: "",
        borderRadius: "",
        bgOpacity: "",
        extraClass: "",
      },
      title: {
        content: "Manage stress effectively with Ashvagandha Himalaya",
        variation: "h4",
        opacity: "text-opacity-100",
        color: "dark",
        startEndorment: "",
        endEndorment: "",
        extraClass: "pt-3",
      },
      paragraph: {
        content:
          "<div><h6>Advertisement</h6><br><h5>Calms nerves, revives mind and body.</h5><br></div>",
        opacity: "text-opacity-100",
        color: "dark",
        extraClass: "pt-2",
      },
      button: [
        {
          content: "Click here",
          variation: "btn-primary",
          size: "w-100",
          position: "right",
          startEndorment: "",
          endEndorment: "",
          extraClass: "py-3 px-4 fw-semibold fs-5",
        },
      ],
      cardStyle: {
        cardbgcolor: "white",
        color: "primary",
        cardbgopacity: "bg-opacity-10",
        border: "",
        borderColor: "",
        borderOpacity: "",
        borderWidth: "rounded-3",
        extraClass: "",
        borderRadius: "",
      },
      imageObject: [
        {
          url: "https://img-cdn.clirnet.com/medwiki/43_server/video/1722859599_1666092616_Ashvagandha_snipped_(1).png",
          position: "bottom-left",
          size: "40px",
          alt: "image text",
          extraClass: "",
        },
      ],
    },
  },
  {
    id: 6,
    name: "Support",
    data: {
      tag: {
        text: "",
        position: "",
        bgColor: "",
        textColor: "",
        borderRadius: "",
        bgOpacity: "",
        extraClass: "",
      },
      title: {
        content: "GET SUPPORT - STAY AHEAD WITH PATIENT CARE",
        variation: "sub_header",
        opacity: "text-opacity-100",
        color: "dark",
        startEndorment: "",
        endEndorment: "",
        extraClass: "pt-3",
      },
      paragraph: {
        content:
          "Our dedicated support team is available to provide timely information and address your inquiries with utmost assistance.",
        opacity: "text-opacity-100",
        color: "dark",
        extraClass: "pt-2 pb-3",
      },
      cardStyle: {
        cardbgcolor: "white",
        color: "primary",
        cardbgopacity: "bg-opacity-10",
        border: "",
        borderColor: "",
        borderOpacity: "",
        borderWidth: "rounded-3",
        extraClass: "",
        borderRadius: "",
      },
      imageObject: [
        {
          url: "",
          position: "",
          size: "",
          alt: "",
          extraClass: "",
        },
      ],
    },
  },
];

export default templateData;
